const banderas = {

    "Argentina":"🇦🇷",
    "Australia":"🇦🇺",
    "Belgium":"🇧🇪",
    "Bosnia-Herzegovina":"🇧🇦",
    "Brazil":"🇧🇷",
    "Canada":"🇨🇦",
    "Colombia":"🇨🇴",
    "Costa Rica":"🇨🇷",
    "Croatia":"🇭🇷",
    "Czechia":"🇨🇿",
    "Denmark":"🇩🇰",
    "Ecuador":"🇪🇨",
    "England":"🏴",
    "France":"🇫🇷",
    "Germany":"🇩🇪",
    "Ghana":"🇬🇭",
    "Iran":"🇮🇷",
    "Italy":"🇮🇹",
    "Japan":"🇯🇵",
    "Mexico":"🇲🇽",
    "Morocco":"🇲🇦",
    "Netherlands":"🇳🇱",
    "New Zealand":"🇳🇿",
    "Nigeria":"🇳🇬",
    "Norway":"🇳🇴",
    "Poland":"🇵🇱",
    "Portugal":"🇵🇹",
    "Qatar":"🇶🇦",
    "Saudi Arabia":"🇸🇦",
    "Scotland":"🏴",
    "Senegal":"🇸🇳",
    "Serbia":"🇷🇸",
    "South Africa":"🇿🇦",
    "South Korea":"🇰🇷",
    "Spain":"🇪🇸",
    "Sweden":"🇸🇪",
    "Switzerland":"🇨🇭",
    "Tunisia":"🇹🇳",
    "Turkey":"🇹🇷",
    "United States":"🇺🇸",
    "Uruguay":"🇺🇾",
    "Wales":"🏴"

};
